import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0a0906",
        surface: "#14120c",
        "surface-dim": "#14120c",
        "surface-bright": "#211c11",
        "surface-variant": "#2c261d",
        "surface-tint": "#d4af37",
        "surface-container-lowest": "#0a0906",
        "surface-container-low": "#1a160f",
        "surface-container": "#1f1a12",
        "surface-container-high": "#262118",
        "surface-container-highest": "#332d24",
        "on-background": "#f9efe4",
        "on-surface": "#f9efe4",
        "on-surface-variant": "#d2c5b1",
        "inverse-surface": "#f9efe4",
        "inverse-on-surface": "#211c11",
        outline: "#807665",
        "outline-variant": "#4e4637",
        primary: "#d4af37",
        "primary-container": "#5c4300",
        "primary-fixed": "#ffdfa0",
        "primary-fixed-dim": "#eec05c",
        "on-primary": "#261a00",
        "on-primary-container": "#ffdfa0",
        "on-primary-fixed": "#ffdfa0",
        "on-primary-fixed-variant": "#ffdfa0",
        "inverse-primary": "#9c7616",
        secondary: "#dcc394",
        "secondary-container": "#554420",
        "secondary-fixed": "#fadfae",
        "secondary-fixed-dim": "#dcc394",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fadfae",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#fadfae",
        tertiary: "#a8c8ff",
        "tertiary-container": "#194780",
        "tertiary-fixed": "#d6e3ff",
        "tertiary-fixed-dim": "#a8c8ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fefcff",
        "on-tertiary-fixed": "#001b3c",
        "on-tertiary-fixed-variant": "#d6e3ff",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#ffffff",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "Newsreader", "serif"],
        body: ["var(--font-newsreader)", "Newsreader", "serif"],
        label: ["var(--font-newsreader)", "Newsreader", "serif"],
        serif: ["var(--font-newsreader)", "Newsreader", "serif"],
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
